### ISSUE TITLE
Discrepancy in DomainSet axis uomLabel

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/OGC-API-Sprint-August-2020#17]
While testing the Cubewerx and PyGeoAPI [server side implementations](https://github.com/opengeospatial/OGC-API-Sprint-August-2020/blob/master/implementations.adoc#server-side-implementations), I found a discrepancy in the uomLabel. 

In https://dev.api.weather.gc.ca/coverages-demo/collections/gdps-temperature/coverage/domainset?f=json, uomLabel is an array containing a `null` value. @tomkralidis 

In https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage/domainset?f=json, uomLabel is a string. @pomakis 

This discrepancy makes JSON parsing difficult. I basically have to ignore the value.

**Comment by tomkralidis** [comment]
thanks @jyutzler. Looks like a bug in pygeoapi.  Fixed and demo updated.  Can you test/report back?

**Comment by jyutzler** [comment]
confirmed :+1:
