### ISSUE TITLE
GeoTIFF

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-API-Sprint-August-2020#2]
How do we expose GeoTIFF through a Coverage API?  

- If it is a Coverage, then it has to contain a domain set and range type.  

- Otherwise, we may have to expose it through the /rangeset path.

Given that very few of the GeoTags in GeoTIFF are mandatory, the answer may depend on the file.

**Comment by pomakis** [comment]
The test implementation that CubeWerx is providing at "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa" treats a GeoTIFF as a coverage.  That is,

```
https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage?f=geotiff
```

returns a GeoTIFF (which in my opinion includes adequate domain set and range type information).

The CIS representation of the domain set and range type can be retrieved separately via the coverage/domainset and coverage/rangetype endpoints respectively.  The links provided by the collection resource explicitly include these three endpoints so the client knows exactly what its options are:

```
    {
      "href": "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage?f=geotiff",
      "rel": "coverage",
      "type": "image/geo+tiff",
      "title": "the coverage of this collection"
    },
    {
      "href": "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage/domainset?f=json",
      "rel": "coverageDomainSet",
      "type": "application/json",
      "title": "the domain set of the coverage of this collection"
    },
    {
      "href": "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage/rangetype?f=json",
      "rel": "coverageRangeType",
      "type": "application/json",
      "title": "the range type of the coverage of this collection"
    },

```
If a coverage had metadata, we'd further expose the following link:

```
    {
      "href": "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED/coverage/metadata?f=json",
      "rel": "coverageMetadata",
      "type": "application/json",
      "title": "the metadata of the coverage of this collection"
    },
```

**Comment by bradh** [comment]
Perhaps orthogonal, but from https://github.com/opengeospatial/geotiff/blob/master/GeoTIFF_Standard/standard/clause_8_media_types.adoc, I think that `type` should be `image/tiff; application=geotiff`

**Comment by pomakis** [comment]
@bradh, Thanks, I wasn't aware of this new(?) recommendation.  Our test service will be adjusted accordingly within the next day or so.

**Comment by jerstlouis** [comment]
> which in my opinion includes adequate domain set and range type information.

I am in strong agreement with this. We will be focusing on GeoTIFF support in our implementation for the sprint.

**Comment by Schpidi** [comment]
I also prefer being able to return GeoTIFFs from `/coverage` although some parts of domain set and range type might not be able to be embedded.

**Comment by cmheazel** [comment]
Proposed extensions to GeoTIFF are welcome.

**Comment by Schpidi** [comment]
Coverages SWG call: There was NOTUC to return GeoTIFFs from the `/coverage` path.

**Comment by jratike80** [comment]
What does NOTUC stand for?

**Comment by pomakis** [comment]
On 03/11/2020 14.52, Jukka Rahkonen wrote:
> What does NOTUC stand for?

"No Objection To Unanimous Consent"

-- 
Keith Pomakis <pomakis@cubewerx.com>
Senior Software Developer, CubeWerx Inc.

**Comment by jratike80** [comment]
Thanks!
